stages:
  - build
  - test
  - deploy

image: nucuriel/php-5.6-node-12.x:1.0.0

variables:
  MYSQL_DATABASE: forum
  MYSQL_USER: homestead
  MYSQL_PASSWORD: secret
  MYSQL_ROOT_PASSWORD: secret

services:
  - name: mysql:5.7.15
    alias: db
  - name: redis:latest
    alias: redis

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  
build:
  stage: build
  image: nucuriel/php-5.6-node-12.x:1.0.0
  script:
    - /usr/local/bin/composer install --no-dev
    - php artisan route:cache; php artisan config:cache; php artisan optimize --force;
    - php artisan migrate:refresh
    - yarn
  only:
    - master
    - develop
  tags:
    - forum