version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    env_file:
      - ./.env
    environment:
      - "APP_ENV=${APP_ENV}"
      - "APP_DEBUG=${APP_DEBUG}"
    networks:
      - mynet
  nginx:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - mynet
  db:
    image: mysql:5.7.15
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
    ports:
        - "3306:3306"
    depends_on:
      - app
    networks:
      - mynet
  redis:
    image: redis
    ports: ["6379"]
    networks:
      - mynet
  elasticsearch:
    image: elasticsearch:5.1.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200
      - 9300
    networks:
      - mynet
  laravel-echo-server:
    build:
      context: ./
      dockerfile: laravel-echo-server.dockerfile
    volumes:
      - ./:/var/www
    ports:
      - 6001:6001
    depends_on:
      - redis
    networks:
      - mynet

volumes:
  dbdata:

networks:
  mynet: